name: build-and-test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      
    defaults:
      run:
        working-directory: src
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Clean
      run: dotnet clean ./FuncSharp.sln --configuration Release && dotnet nuget locals all --clear

    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --logger "trx;LogFileName=test-results.trx" || true

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Mews.FuncSharp Tests report
        path: "**/test-results.trx"
        reporter: dotnet-trx
        fail-on-error: true